Resources:
  EC2Server:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c76bd4bd302b30ec
      InstanceType: t2.micro
      SecurityGroupIds:
        - gre_sg
      KeyName: gre_kp
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 25
